// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWYAQ7ZQNoppa_bluR8PcVwUoaw-xUeOc',
    appId: '1:1086999134216:web:aaa1b4bdec43e2ae5c11bd',
    messagingSenderId: '1086999134216',
    projectId: 'vibrationappcommunication',
    authDomain: 'vibrationappcommunication.firebaseapp.com',
    storageBucket: 'vibrationappcommunication.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9wDay0wgqsnDAmX33Uzd-ReCrgdgHAUk',
    appId: '1:1086999134216:android:ce641dbd77512f9b5c11bd',
    messagingSenderId: '1086999134216',
    projectId: 'vibrationappcommunication',
    storageBucket: 'vibrationappcommunication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_fD2tA0-F9u14LJBkiJoP3wpu3rC2LvI',
    appId: '1:1086999134216:ios:9c972929731098415c11bd',
    messagingSenderId: '1086999134216',
    projectId: 'vibrationappcommunication',
    storageBucket: 'vibrationappcommunication.firebasestorage.app',
    iosBundleId: 'com.example.vibrationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_fD2tA0-F9u14LJBkiJoP3wpu3rC2LvI',
    appId: '1:1086999134216:ios:9c972929731098415c11bd',
    messagingSenderId: '1086999134216',
    projectId: 'vibrationappcommunication',
    storageBucket: 'vibrationappcommunication.firebasestorage.app',
    iosBundleId: 'com.example.vibrationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWYAQ7ZQNoppa_bluR8PcVwUoaw-xUeOc',
    appId: '1:1086999134216:web:a6cdac7ca05bdb1a5c11bd',
    messagingSenderId: '1086999134216',
    projectId: 'vibrationappcommunication',
    authDomain: 'vibrationappcommunication.firebaseapp.com',
    storageBucket: 'vibrationappcommunication.firebasestorage.app',
  );
}
